config/routes.php
    <?php

/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('Route');

Router::scope('/usuario', ['controller' => 'Users'], function ($routes) {
    $routes->connect('/sem-permissao', ['action' => 'noPermission']);
    $routes->connect('/login', ['action' => 'login']);
    $routes->connect('/logout', ['action' => 'logout']);
    $routes->connect('/cadastrar', ['action' => 'add']);
    $routes->connect('/listar', ['action' => 'index']);
    $routes->connect('/visualizar/*', ['action' => 'view']);
    $routes->connect('/editar/*', ['action' => 'edit']);
});

Router::scope('/paciente', ['controller' => 'Patients'], function ($routes) {
    $routes->connect('/cadastrar', ['action' => 'add']);
    $routes->connect('/listar', ['action' => 'index']);
    $routes->connect('/visualizar/*', ['action' => 'view']);
    $routes->connect('/editar/*', ['action' => 'edit']);
});

Router::scope('/profissional', ['controller' => 'Professionals'], function ($routes) {
    $routes->connect('/cadastrar', ['action' => 'add']);
    $routes->connect('/listar', ['action' => 'index']);
    $routes->connect('/visualizar/*', ['action' => 'view']);
    $routes->connect('/editar/*', ['action' => 'edit']);
});

Router::scope('/permissao', ['controller' => 'Permissions'], function ($routes) {
    $routes->connect('/unidade', ['action' => 'organizations']);
    $routes->connect('/adicionar/*', ['action' => 'add']);
});

Router::scope('/indicadores', ['controller' => 'Indicators'], function ($routes) {
    $routes->connect('/demograficos', ['action' => 'demographic']);
});

Router::scope('/papel', ['controller' => 'Roles'], function ($routes) {
    $routes->connect('/cadastrar', ['action' => 'add']);
    $routes->connect('/listar', ['action' => 'index']);
    $routes->connect('/editar/*', ['action' => 'edit']);
});

Router::scope('/acao', ['controller' => 'Actions'], function ($routes) {
    $routes->connect('/cadastrar', ['action' => 'add']);
    $routes->connect('/listar', ['action' => 'index']);
    $routes->connect('/editar/*', ['action' => 'edit']);
});

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

//  $routes->connect('/sem-permissao', ['controller' => 'Pages', 'action' => 'display', 'inactive_user']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `InflectedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'InflectedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'InflectedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('InflectedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/UsersTable.php
<?php

namespace App\Model\Table;

use App\Model\Entity\User;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 */
class UsersTable extends Table {

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config) {
        $this->table('users');
        $this->displayField('id');
        $this->primaryKey('id');
        $this->addBehavior('Timestamp');

        $this->belongsTo('Organizations', [
            'foreignKey' => 'organization_id'
        ]);
        $this->belongsTo('People', [
            'foreignKey' => 'person_id'
        ]);
        $this->hasMany('Permissions', [
            'foreignKey' => 'user_id'
        ]);
        $this->belongsTo('Admins', [
            'classname' => 'Users',
            'foreignKey' => 'admin_id'
        ]);
    }
    
    /**
     * Verifica se as duas senhas digitadas são idênticas
     * 
     * @param type $field  Primeira senha digitada
     * @param type $record Todas as informações relativas ao usuário
     * @return boolean
     */
    public function requireVerification($field, $record) {
        if(!empty($field) && $field != $record['data']['retype_password']) {
            return false;
        }
        return true;
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator) {
        $validator
                ->add('id', 'valid', ['rule' => 'numeric'])
                ->allowEmpty('id', 'create');

        $validator
                ->add('person_id', 'valid', ['rule' => 'numeric'])
                ->allowEmpty('person_id', 'create');

        $validator
                ->add('organization_id', 'valid', ['rule' => 'numeric'])
                ->allowEmpty('organization_id', 'create');

        $validator
                ->requirePresence('username', 'create')
                ->notEmpty('username', 'Campo obrigatório', 'create');

        $validator
                ->add('password', ['require_verification' => ['rule' => [$this,'requireVerification'], 'message' => 'Preencha o campo abaixo']])
                ->requirePresence('password', 'create')
                ->notEmpty('password', 'Campo obrigatório', 'create');
              
        $validator
                ->add('retype_password', ['isEqual' => ['rule' => ['compareWith', 'password'], 'message' => 'As senhas devem ser idênticas']])
                ->requirePresence('retype_password', 'create')
                ->notEmpty('retype_password', 'Campo obrigatório', 'create');
        
        $validator
                ->add('active', 'valid', ['rule' => 'boolean'])
                ->requirePresence('active', 'create')
                ->notEmpty('active', 'create');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules) {
        $rules->add($rules->existsIn(['person_id'], 'People', 'O profissionals precisa existir'));
        $rules->add($rules->existsIn(['organization_id'], 'Organizations', 'A unidade precisa existir'));
        $rules->add($rules->isUnique(['username'], 'Usuário já existente'));
        return $rules;
    }

    /**
     * Encontra os usuários que um usuário pode ver.
     * Existem duas formas de visualização:
     * 
     * Somente ususários locais $local_only = true ou
     * todos os usuários, nesse caso, $local_only = false
     * 
     * @param Query $query
     * @param array $options
     * @return type
     */
    public function findAllowed(Query $query, array $options) {
        $fields = ['Users.id'];

        $query = $this->find()
                ->distinct($fields)
                ->contain(['People', 'Organizations']);
        if ($options['local_only']) {
            $query = $this->find()->distinct($fields)
                    ->contain(['People', 'Organizations'])
                    ->matching('Permissions', function ($q) use ($options) {
                        return $q->where(['Permissions.organization_id' => $options['organization_id']])
                                 ->distinct();
            });
        }
        return $query;
    }

}

src/Template/Element/action_form.ctp
<?php echo $this->Form->create($action); ?>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-md-6 col-lg-4">
        <h6>(*) Campos Obrigatórios</h6>
        <fieldset>
            <br/>
            <div class="form-group">
                <label class="control-label"><?= __('Nome da Acão') ?> *</label>
                <?php echo $this->Form->input('name', ['class' => 'form-control', 'label' => false]); ?>
            </div>
            <div class="form-group">
                <label class="control-label"><?= __('Controller') ?> *</label>
                <?php echo $this->Form->input('controller', ['class' => 'form-control', 'label' => false]); ?>
            </div>
            <div class="form-group">
                <label class="control-label"><?= __('Action') ?> *</label>
                <?php echo $this->Form->input('action', ['class' => 'form-control', 'label' => false]); ?>
            </div>
            <div class="form-group">
                <label class="control-label"><?= __('Vincular a papéis') ?> *</label>
                <?php echo $this->Form->input('roles._ids', ['options' => $roles, 'class' => 'form-control', 'label' => false]); ?>
            </div>
        </fieldset>
        <?= $this->Form->submit(__('Salvar'), ['class' => 'btn btn-success']) ?>
        <?= $this->Form->end() ?>
    </div>
</div>

src/Template/Element/patient_info.ctp
<?php
if (empty($patient->person->birthdate)) {
    $age = $patient->approximate_age . " ANOS (aproximada)";
} else {
    $birthdate = DateTime::createFromFormat("Y-m-d", $patient->person->birthdate->format('Y-m-d'));
    $age = $birthdate->diff(new DateTime())->format('%Y') . " ANOS";
}

if ($patient->person->gender == "M") {
    $gender = 'MASCULINO';
} elseif ($patient->person->gender == "F") {
    $gender = 'FEMININO';
} else {
    $gender = 'TRANSSEXUAL';
}
?>

<ul class="list-inline">
    <li>
        <h4><?= __('Nome') ?></h4>
        <p class="blue-text white-box"><?php echo $patient->person->name; ?></p>
    </li>
    <li>
        <h4><?= __('CNS') ?></h4>
        <p class="blue-text white-box"><?php echo empty($patient->cns) ? __('NÃO DISPONÍVEL') : $patient->cns; ?></p>
    </li>
    <li>
        <h4><?= __('Sexo') ?></h4>
        <p class="blue-text white-box"><?= h($gender) ?></p>
    </li>
    <li>
        <h4><?= __('Idade') ?></h4>
        <p class="blue-text white-box"><?php echo $age; ?></p>
    </li>
</ul>

src/Template/Element/professional_info.ctp
<?php
if ($professional->person->gender == "M") {
    $gender = 'MASCULINO';
} elseif ($professional->person->gender == "F") {
    $gender = 'FEMININO';
} else {
    $gender = 'TRANSSEXUAL';
}
?>

<ul class="list-inline">
    <li>
        <h4><?= __('Nome') ?></h4>
        <p class="blue-text white-box"><?php echo $professional->person->name; ?></p>
    </li>
    <li>
        <h4><?= __('Sexo') ?></h4>
        <p class="blue-text white-box"><?= h($gender) ?></p>
    </li>
</ul>

src/Template/Element/role_form.ctp
<?php
    $domains = ['sistema' => 'Sistema', 'caps' => 'Caps', 'sisam' => 'Sisam', 'ubs' => 'UBS', 'residencia_terapeutica' => 'Residência Terapêutica'];
?>
<?php echo $this->Form->create($role); ?>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-md-6 col-lg-4">
        <h6>(*) Campos Obrigatórios</h6>
        <fieldset>
            <br/>
            <div class="form-group">
                <label class="control-label"><?= __('Nome do Papel') ?> *</label>
                <?php echo $this->Form->input('name', ['class' => 'form-control', 'label' => false]); ?>
            </div>
            <div class="form-group">
                <label class="control-label"><?= __('Domínio') ?> *</label>
                <?php echo $this->Form->input('domain', ['options' => $domains, 'empty' => true, 'class' => 'form-control', 'label' => false]); ?>
            </div>
            <div class="form-group">
                <label class="control-label"><?= __('Ações permitidas') ?> *</label>
                <?php echo $this->Form->input('actions._ids', ['options' => $actions, 'class' => 'form-control', 'label' => false]); ?>
            </div>
        </fieldset>
        <?= $this->Form->submit(__('Salvar'), ['class' => 'btn btn-success']) ?>
        <?= $this->Form->end() ?>
    </div>
</div>

src/Template/Element/user_info.ctp
<ul class="list-inline" style="display: inline-block">
    <li>
        <h4><?= __('Nome') ?></h4>
        <p class="blue-text white-box"><?php echo (!empty($user->person->name) ? h($user->person->name) : h($user->organization->name)); ?></p>
    </li>
    <li>
        <h4><?= __('Cadastro') ?></h4>
        <p class="blue-text white-box"><?= h($user->created->format('d/m/Y')) ?></p>
    </li>
    <li>
        <h4><?= __('Ativo') ?></h4>
        <p class="blue-text white-box"><?= $user->active ? __('SIM') : __('NÃO'); ?></p>
    </li>
</ul>